admin_homepage:
    path: /admin
    defaults: { _controller: AdminBundle:Default:index }

admin_ajout:
    path: /admin-ajout
    defaults: { _controller: AdminBundle:Default:ajout }

admin_modif:
    path: /admin-modif-{id}
    defaults: { _controller: AdminBundle:Default:modif }
    requirements:
        id: '\d+'

admin_enonce:
    path: /admin-enonce
    defaults: { _controller: AdminBundle:Default:enonce }

admin_devoir:
    path: /admin-devoir-{id}
    defaults: { _controller: AdminBundle:Default:devoir }
    requirements:
        id: '\d+'

hint_modif:
    path: /admin-modif
    defaults: { _controller: AdminBundle:Default:hint }

admin_suppr:
    path: /admin-suppr/{id}
    defaults: { _controller: AdminBundle:Default:suppr }
    requirements:
        id: '\d+'

admin_form:
    # qui cree un form (dans la div front) qui aura un textarea ou un input file (image)
    path: /admin-form
    defaults: { _controller: AdminBundle:Default:form }

admin_classe:
    path: /admin-classe-{id}
    defaults: { _controller: AdminBundle:Default:classe }
    requirements:
        id: '\d+'

admin_enonce_modif:
    path: /admin-enonce-modif-{id}
    defaults: { _controller: AdminBundle:Default:modifEnonce }
    requirements:
        id: '\d+'

test:
    path: /admin-test
    defaults: { _controller: AdminBundle:Default:test }