<?php

namespace AppBundle\Repository;

/**
 * EnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
