AppBundle\Entity\Devoir:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DevoirRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        classe:
            type: integer
        titre:
            type: string
            length: 255
        date:
            type: datetime
    lifecycleCallbacks: {  }
